"""
infra/e2b_exporter.py
======================
ICH E2B(R3) XML serializer for finalized ICSR pipeline state.

Converts the output of ICSRPipeline.run_case() / resume_case() into a
well-formed ICH E2B(R3) (CIOMS XI) XML document suitable for:
  - Internal regulatory review (QPPV pre-submission workflow)
  - Sandbox submissions to EudraVigilance / MedWatch test environments
  - Import into commercial safety databases (Argus, ARISg, etc.)

IMPORTANT — MedDRA Licensing (ADR-001):
  This implementation uses CTCAE v5 preferred terms in <reactionmeddrapt>
  because MedDRA is a commercially licensed terminology (MSSO). A structured
  XML comment is inserted at each reaction element to flag this for the QPPV.
  See governance/decisions.md ADR-001 for the full rationale and upgrade path.

  To integrate MedDRA coding (for licence holders), supply a `meddra_mapper`
  callable to the constructor:
    exporter = E2BExporter(meddra_mapper=my_ctcae_to_meddra_llt_function)

E2B(R3) reference: ICH M2 / E2B(R3) Implementation Guide (EMA/INS/GCP/580859/2018)

Usage:
  from infra.e2b_exporter import E2BExporter

  exporter = E2BExporter()
  xml_str  = exporter.export(state=pipeline_state, case_id="ICSR-2024-001")
"""
from __future__ import annotations

import os
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Any, Callable

# E2B(R3) namespace / schema declaration
_E2B_DOCTYPE = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!-- ICH E2B(R3) ICSR — Generated by ICSR Multi-Agent Pipeline v0.6.0 -->\n'
    '<!-- See governance/decisions.md ADR-001 for MedDRA licensing rationale -->\n'
)

_MEDDRA_ADR_COMMENT = (
    "MedDRA LLT/PT required for regulatory submission. "
    "Current value is CTCAE v5 preferred term. "
    "Organisations holding a valid MedDRA licence may integrate the "
    "CTCAE-to-MedDRA crosswalk to make this export fully E2B(R3) compliant. "
    "See governance/decisions.md ADR-001."
)

# WHO-UMC causality → E2B(R3) drugcharacterization mapping
# 1=Suspect, 2=Concomitant, 3=Interacting
_CAUSALITY_TO_CHAR: dict[str, str] = {
    "CERTAIN":        "1",
    "PROBABLE":       "1",
    "POSSIBLE":       "1",
    "UNLIKELY":       "2",
    "UNCLASSIFIABLE": "2",
    "UNASSESSABLE":   "2",
}

# Seriousness → E2B(R3) seriousness flags
_TIER_SERIOUS: dict[str, bool] = {
    "TIER_1": True,
    "TIER_2": True,
    "TIER_3": False,
}


def _utcnow_e2b() -> str:
    """Return current UTC time in E2B(R3) datetime format: YYYYMMDDHHmmss."""
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")


def _safe_text(val: Any, max_len: int = 2000) -> str:
    """Convert value to safe XML text string."""
    if val is None:
        return ""
    return str(val)[:max_len]


def _sub(parent: ET.Element, tag: str, text: str = "") -> ET.Element:
    el = ET.SubElement(parent, tag)
    if text:
        el.text = text
    return el


class E2BExporter:
    """
    Serializes a finalized ICSR pipeline state to ICH E2B(R3) XML.

    Parameters
    ----------
    meddra_mapper : Callable[[str], str] | None
        Optional function that accepts a CTCAE preferred term and returns
        the corresponding MedDRA LLT code (as string). If None, CTCAE term
        is used as free-text with an ADR-001 comment. Required only when
        the organisation holds a valid MedDRA licence.
    sender_id : str
        E2B(R3) <senderorganization> value (default: env E2B_SENDER_ORG).
    receiver_id : str
        E2B(R3) <receiverorganization> value (default: env E2B_RECEIVER_ORG).
    """

    def __init__(
        self,
        meddra_mapper: Callable[[str], str] | None = None,
        sender_org:    str | None = None,
        receiver_org:  str | None = None,
    ) -> None:
        self._meddra_mapper = meddra_mapper
        self._sender_org    = sender_org or os.getenv("E2B_SENDER_ORG",   "ICSR-HITL-SYSTEM")
        self._receiver_org  = receiver_org or os.getenv("E2B_RECEIVER_ORG", "REGULATORY-AUTHORITY")
        self._sender_id     = os.getenv("E2B_SENDER_ID",   "SENDER-001")
        self._receiver_id   = os.getenv("E2B_RECEIVER_ID", "RECEIVER-001")

    def export(self, state: dict[str, Any], case_id: str) -> str:
        """
        Convert finalized pipeline state to ICH E2B(R3) XML string.

        Parameters
        ----------
        state   : dict — finalized pipeline state (from run_case / resume_case)
        case_id : str  — ICSR case identifier

        Returns
        -------
        str — well-formed E2B(R3) XML document
        """
        root = ET.Element("ichicsr", attrib={"lang": "en"})

        # ── Message header ────────────────────────────────────────────────────
        self._build_header(root, case_id)

        # ── Safety report ─────────────────────────────────────────────────────
        report = _sub(root, "safetyreport")
        _sub(report, "safetyreportid",          case_id)
        _sub(report, "safetyreportversion",     "1")
        _sub(report, "receiptdate",             _utcnow_e2b()[:8])
        _sub(report, "receiptdateformat",       "102")   # YYYYMMDD
        _sub(report, "primarysourcecountry",    self._extract_country(state))
        _sub(report, "occurcountry",            self._extract_country(state))
        _sub(report, "transmissiondate",        _utcnow_e2b()[:8])
        _sub(report, "transmissiondateformat",  "102")

        # Seriousness flags
        self._build_seriousness(report, state)

        # Source type
        _sub(report, "primarysource", "")

        # Patient block (drugs + reactions)
        patient = _sub(report, "patient")
        self._build_patient(patient, state)

        # Narrative
        narrative = _safe_text(state.get("final_narrative", ""))
        _sub(report, "narrativeincludeclinical", narrative)

        # ── Sender / Receiver ─────────────────────────────────────────────────
        self._build_sender(root)
        self._build_receiver(root)

        # Serialise
        tree  = ET.ElementTree(root)
        ET.indent(tree, space="  ")
        xml_body = ET.tostring(root, encoding="unicode", xml_declaration=False)
        return _E2B_DOCTYPE + xml_body

    # ── Private builders ──────────────────────────────────────────────────────

    def _build_header(self, root: ET.Element, case_id: str) -> None:
        hdr = _sub(root, "ichicsrmessageheader")
        _sub(hdr, "messagetype",           "ichicsr")
        _sub(hdr, "messageformatversion",  "2.1")
        _sub(hdr, "messageformatrelease",  "2.0")
        _sub(hdr, "messagenumb",           case_id)
        _sub(hdr, "messagesenderidentifier",   self._sender_id)
        _sub(hdr, "messagereceiveridentifier", self._receiver_id)
        _sub(hdr, "messagedateformat",     "204")   # YYYYMMDDHHmmss
        _sub(hdr, "messagedate",           _utcnow_e2b())

    def _extract_country(self, state: dict) -> str:
        entities = state.get("extracted_entities") or {}
        if isinstance(entities, dict):
            return _safe_text(entities.get("country_of_primary_reporter", ""), 2)
        return ""

    def _build_seriousness(self, report: ET.Element, state: dict) -> None:
        triage = state.get("triage_output") or {}
        tier   = str(triage.get("risk_tier", "TIER_3")).upper()
        serious = "1" if _TIER_SERIOUS.get(tier, False) else "2"
        _sub(report, "serious",              serious)
        _sub(report, "seriousnessdeath",     "2")
        _sub(report, "seriousnesslifethreatening", "1" if tier == "TIER_1" else "2")
        _sub(report, "seriousnesshospitalisation", serious)
        _sub(report, "seriousnessdisabling",       "2")
        _sub(report, "seriousnesscongenitalanomali", "2")
        _sub(report, "seriousnessother",            serious)

    def _build_patient(self, patient: ET.Element, state: dict) -> None:
        entities = state.get("extracted_entities") or {}
        if isinstance(entities, dict):
            sex_map = {"MALE": "1", "FEMALE": "2", "UNKNOWN": "0"}
            sex = sex_map.get(str(entities.get("patient_sex", "")).upper(), "0")
            _sub(patient, "patientsex",      sex)
            age = _safe_text(entities.get("patient_age", ""))
            if age:
                _sub(patient, "patientonsetage",       age)
                _sub(patient, "patientonsetageunit",   "801")   # years

        # Drugs
        self._build_drugs(patient, state)
        # Reactions
        self._build_reactions(patient, state)

    def _build_drugs(self, patient: ET.Element, state: dict) -> None:
        entities = state.get("extracted_entities") or {}
        drugs    = []
        if isinstance(entities, dict):
            drugs = entities.get("suspect_drugs") or []
        if not isinstance(drugs, list):
            drugs = [drugs] if drugs else []

        causality_matrix = state.get("causality_matrix") or {}

        for drug_entry in drugs:
            if isinstance(drug_entry, dict):
                drug_name = _safe_text(drug_entry.get("name") or drug_entry.get("drug_name", ""))
                rxnorm_cui = _safe_text(drug_entry.get("rxnorm_cui", ""))
            else:
                drug_name  = _safe_text(drug_entry)
                rxnorm_cui = ""

            if not drug_name:
                continue

            drug_el = _sub(patient, "drug")

            # WHO-UMC causality → drugcharacterization
            causal_term = "POSSIBLE"
            if isinstance(causality_matrix, dict):
                causal_term = str(causality_matrix.get(drug_name, causal_term)).upper()
            char_code = _CAUSALITY_TO_CHAR.get(causal_term, "1")

            _sub(drug_el, "drugcharacterization",     char_code)
            _sub(drug_el, "medicinalproduct",          drug_name)
            if rxnorm_cui:
                _sub(drug_el, "drugbatchnumb",         "")
                prod_id = _sub(drug_el, "drugproductid")
                prod_id.text = rxnorm_cui
                prod_id.set("type", "RxNorm")
            _sub(drug_el, "drugcausalityassessment",   causal_term)
            _sub(drug_el, "actiondrug",                "6")   # unknown

    def _build_reactions(self, patient: ET.Element, state: dict) -> None:
        coded_events = state.get("coded_events") or []
        if not isinstance(coded_events, list):
            coded_events = [coded_events] if coded_events else []

        for event in coded_events:
            if isinstance(event, dict):
                term = _safe_text(
                    event.get("preferred_term")
                    or event.get("ctcae_term")
                    or event.get("term", "")
                )
            else:
                term = _safe_text(event)

            if not term:
                continue

            reaction = _sub(patient, "reaction")
            _sub(reaction, "primarysourcereaction", term)

            # MedDRA — ADR-001: use CTCAE term with structured comment
            meddra_el = ET.SubElement(reaction, "reactionmeddrapt")
            if self._meddra_mapper is not None:
                try:
                    meddra_el.text = self._meddra_mapper(term)
                except Exception:
                    meddra_el.text = term
                    meddra_el.append(ET.Comment(_MEDDRA_ADR_COMMENT))
            else:
                meddra_el.text = term
                meddra_el.append(ET.Comment(_MEDDRA_ADR_COMMENT))

            _sub(reaction, "reactionoutcome", "6")   # unknown

    def _build_sender(self, root: ET.Element) -> None:
        sender = _sub(root, "sender")
        _sub(sender, "sendertype",             "5")   # Other
        _sub(sender, "senderorganization",      self._sender_org)
        _sub(sender, "senderfamilyname",        "")
        _sub(sender, "sendergivename",          "")
        _sub(sender, "senderstreetaddress",     "")
        _sub(sender, "sendercountrycode",       "")
        _sub(sender, "sendertel",               "")
        _sub(sender, "senderemail",             "")

    def _build_receiver(self, root: ET.Element) -> None:
        receiver = _sub(root, "receiver")
        _sub(receiver, "receivertype",          "6")   # Regulatory authority
        _sub(receiver, "receiverorganization",   self._receiver_org)
        _sub(receiver, "receivercountrycode",    "")
